### ISSUE TITLE
Windows版本file diff时出错

### ISSUE THREAD

**Issue by yantaozhao** [huizhougit/githd#21]
Linux系统上: OK.
Windows系统上: 使用file diff时,提示`Unable to open ...`错误. log信息如下:

[renderer1] [error] Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
	at BlameViewProvider.<anonymous> (C:\Users\DELL\.vscode\extensions\huizhou.githd-2.0.0\out\src\blameViewProvider.js:145:33)
	at Generator.next (<anonymous>)
	at C:\Users\DELL\.vscode\extensions\huizhou.githd-2.0.0\out\src\blameViewProvider.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\DELL\.vscode\extensions\huizhou.githd-2.0.0\out\src\blameViewProvider.js:3:12)
	at BlameViewProvider._onDidChangeActiveTextEditor (C:\Users\DELL\.vscode\extensions\huizhou.githd-2.0.0\out\src\blameViewProvider.js:144:16)
	at BlameViewProvider.vscode_1.window.onDidChangeActiveTextEditor.editor (C:\Users\DELL\.vscode\extensions\huizhou.githd-2.0.0\out\src\blameViewProvider.js:63:22)
	at e.fire (d:\Program Files\MicrosoftVSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at d:\Program Files\MicrosoftVSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:588:237
	at e.fire (d:\Program Files\MicrosoftVSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at e.$acceptDocumentsAndEditorsDelta (d:\Program Files\MicrosoftVSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:488:823)
	at t._doInvokeHandler (d:\Program Files\MicrosoftVSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:888)
	at t._invokeHandler (d:\Program Files\MicrosoftVSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:554)
	at t._receiveRequest (d:\Program Files\MicrosoftVSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:126)
	at t._receiveOneMessage (d:\Program Files\MicrosoftVSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:59)
	at d:\Program Files\MicrosoftVSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:926
	at d:\Program Files\MicrosoftVSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
	at e.fire (d:\Program Files\MicrosoftVSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at a (d:\Program Files\MicrosoftVSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:213)
	at Socket._socketDataListener (d:\Program Files\MicrosoftVSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)

**Comment by yantaozhao** [comment]
不能使用diff功能，暂未发现影响别的功能。

git是在path环境里的:
```sh
C:\Users\DELL> git --version
git version 2.19.1.windows.1

C:\Users\DELL> where git
d:\Program Files\Git\cmd\git.exe
```

**Comment by huizhougit** [comment]
@yantaozhao Could you reproduce it with verbose trace enabled?
1. `ctrl+,` to open the settings
2. search _**githd**_
3. change _**Trace Level**_ to verbose
4. `Ctrl+Shift+u` to open Output window, select GitHD as the output
5. reproduce the issue and see what's the trace output

**Comment by lanrain** [comment]
我的也是比较时，出现错误，什么都不展示，按照你说的设置，调整后输出的内容如下：
```
[04:16:20.452][Verbose] Command: githd.openCommittedFile
[04:16:20.478][Info] _onDidChangeActiveTextEditor with null or undefined editor
```

**Comment by htjain** [comment]
+1 I am also seeing this issue with vs remote ssh project
