### ISSUE TITLE
TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by foxundermoon** [huizhougit/githd#25]
```
  ERR Cannot read property 'trim' of undefined: TypeError: Cannot read property 'trim' of undefined
    at GitService.<anonymous> (/Users/fox/.vscode/extensions/huizhou.githd-2.1.0/out/src/gitService.js:369:35)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/fox/.vscode/extensions/huizhou.githd-2.1.0/out/src/gitService.js:4:58)
    at propagateAslWrapper (/Users/fox/.vscode/extensions/vscjava.vscode-java-debug-0.16.0/node_modules/async-listener/index.js:504:23)
    at /Users/fox/.vscode/extensions/vscjava.vscode-java-debug-0.16.0/node_modules/async-listener/index.js:541:70
    at <anonymous>
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:228:7)
```

**Comment by huizhougit** [comment]
Does it always happen?

**Comment by foxundermoon** [comment]
yes.  must be bappen!

![image](https://user-images.githubusercontent.com/2764106/51450668-7cdc5a00-1d6c-11e9-822f-909854b7fa46.png)

**Comment by ctq123** [comment]
+1
